name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      image-name: cayers-sample-app
    steps:
    - uses: actions/checkout@v3
    - name: Set current date as ENV var
      id: date
      run: echo "::set-output name=date::$(date +%s)" 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image-name }}:${{ steps.date.outputs.date }}
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        # Docker image to scan
        image-name: ${{ env.image-name }}:${{ steps.date.outputs.date }}
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        token: ${{ github.token }}

  deploy-image:
    runs-on: ubuntu-latest
    env:
      image-name: cayers-sample-app
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
          docker build . -t ${{ secrets.ACR_URL }}/${{ env.image-name }}:${{ github.sha }}
          docker push ${{ secrets.ACR_URL }}/${{ env.image-name }}:${{ github.sha }}
