name: Docker Image push to Registries

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      image-name: cayers-sample-app
    steps:
    - uses: actions/checkout@v4
    - name: Set current date as ENV var
      id: date
      run: echo "::set-output name=date::$(date +%s)" 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image-name }}:${{ steps.date.outputs.date }}
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        # Docker image to scan
        image-name: ${{ env.image-name }}:${{ steps.date.outputs.date }}
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        token: ${{ github.token }}
    - uses: azure/login@v2
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: ${{ env.image-name }}:${{ steps.date.outputs.date }}
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        # Docker image to scan
        image-name: ${{ env.image-name }}:${{ steps.date.outputs.date }}
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        token: ${{ github.token }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.image-name }}:${{ steps.date.outputs.date }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.image-name }}:latest
          ${{ secrets.DOCKER_USERNAME }}/${{ env.image-name }}:${{ github.sha }}
          ${{ secrets.ACR_URL }}/${{ env.image-name }}:latest
          ${{ secrets.ACR_URL }}/${{ env.image-name }}:${{ github.sha }}
