name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tag-name: my-image-name
    steps:
    - uses: actions/checkout@v3
    - name: Set current date as ENV var
      id: date
      run: echo "::set-output name=date::$(date +%s)" 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.tag-name }}:${{ steps.date.outputs.date }}
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        # Docker image to scan
        image-name: ${{ env.tag-name }}:${{ steps.date.outputs.date }}
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        token: ${{ github.token }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.tag-name }}:${{ steps.date.outputs.date }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'