name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tag-name: my-image-name
    steps:
    - uses: actions/checkout@v7
    - name: Set current date as ENV var
      id: date
      run: echo "date=$(date +%s)" >> "$GITHUB_OUTPUT"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.tag-name }}:${{ steps.date.outputs.date }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: '${{ env.tag-name }}:${{ steps.date.outputs.date }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
